# Docs: <https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/customizing-dependency-updates>

version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule: {interval: monthly}
    reviewers: [freifunkMUC/wg-access-server]
    assignees: [freifunkMUC/wg-access-server]
